### PR TITLE
Added power support for the travis.yml file with ppc64le

### PR DESCRIPTION
**Pull request by sreekanth370**
Added power support for the travis.yml file with ppc64le. This is part of the Ubuntu distribution for ppc64le. This helps us simplify testing later when distributions are re-building and re-releasing.

### CODE REVIEW

**Comment by yunhaoling** [comment]
hey @lmazuel @annatisch , could you take a look at this PR?

**Comment by annatisch** [comment]
Thanks @yunhaoling - the changes look fine, though I don't really know enough about this arch to be able to comment on the output - are we able to confirm that these wheels work as expected?
Also it may need updating for 3.9.

**Comment by yunhaoling** [comment]
hello @sreekanth370, your PR looks good, however, as we're not quite familiar with ppc64le arch, could you please explain the purpose of your PR a bit more in detail?

Based on what you have given, we know that ppc64le is a CPU architecture and there is a ubuntu distribution (ubuntu for POWER?)
- are you running the azure-uamqp-python(or any libraries that users uamqp) on ppc64le ubuntu or just for the purpose of environment test
- how could updating the travis ci yml "simplify testing later when distributions are re-building and re-releasing", can you give some details on this one? like what steps do you usually do for re-building and re-releasing.

thank you for your knowledge in advance😊

**Comment by sreekanth370** [comment]
Thanks for your response and tag for more info @gerrith3 (

**Comment by yunhaoling** [comment]
hey @gerrith3, could you kindly provide more context about the ppc64le support?

**Comment by gerrith3** [comment]
@yunhaoling sure...  IBM has two additional hardware architectures that we build/sell and both fully support Linux (s390x for System Z/LinuxONE and ppc64le for Power).  Both have several Linux distros that are built for the architecture which we use as a base  when shipping hardware and building other open source and 3rd party applications.  These platforms are widely used globally as part of the Global 1000 customers.  Recently we have been trying to reduce our costs and the amount of replication in supporting multiple distros and are working to get more open source projects to test as changes are made rather than trying to find all problems at the point in time when each distro pulls bits for its next release.  This is similar to the way the Linux kernel community and many other base communities already work - testing on all available platforms (and sometimes with a variety of distros/compilers/interpreters/environments) for each patch.  This moves problem resolution to happen when developers make the change rather than us having to work with the distributions months (or longer) after a change has been made and try to understand without the original developer's context exactly why this regression happened.  This has started now because we have finally set up a public cloud with broad, easy access to Power (and s390x/Z) servers and Travis CI as a front to that cloud, meaning we can now provide a CI more widely to open source communities.  We are trying to help communities jump start with the extended Travis testing on Power by building the project on Power, then building on Travis, evaluating any changes needed to the .travis.yml and them submitting the pull request to the community when we have a complete build and all tests passing.

Feel free to tag me with any more specific questions - I tried to throw in a broad overview here but if I missed your question just let me know.

**Comment by yunhaoling** [comment]
hey folks, I apologize for the late update.
we've decided to deprecate travis for CI and switch to devops for the CI purpose.

For multi-platform wheel support, our plan is to work on pure python amqp library which currently stays in the `pyproto` branch.

I'm closing this PR since the file is about to be removed, but feel free to open issues and we would be glad to help.

**Pull request closed without merging**
